### ISSUE TITLE
Display info about "remote" working possibilities

### ISSUE THREAD

**Issue by domis86** [norberttech/hire-in-social#94]
1. On the "home / search" would be good to show info about "remote" working possibility. There is "remote" filter, but on each offer you dont see if is remote.
2. On the page of specific job offer there is:
```
Work Type
Partially Remote 

or

Work Type
At Office
```
  * ^ probably also "Fully remote" option should be possible there
3. On search page there is "remote" filter - but is a flag (on or off). Maybe it should be changed to select, or radio/checkboxes - so you can search for specific remote type: at office, partially, full

**Comment by norberttech** [comment]
It's actually working this way on purpose, when "Remote" is selected in offers search it will look for any type of remote jobs, fully and partially remote. It might not be the best solution but without data it's hard to say whats the best. This feature might be changed in the future after release
